### ISSUE TITLE
Support for incremental build and build cache

### ISSUE THREAD

**Issue by ghilainm** [rackerlabs/gradle-jaxb-plugin#42]
For the moment despite not changing any XSD, neither bindings schema. I can't benefit from the incremental build and Gradle doesn't stop to say me that the build cache feature was not enabled.

I guess you need to define output and intput of the task in the plugin in order to achieve this. Is it already done?

Example:
> Task :ics-api:xjc
Build cache key for task ':ics-api:xjc' is b1d82cc592bc9820e517153dfcf8397f
Caching disabled for task ':ics-api:xjc': Caching has not been enabled for the task

**Comment by wdschei** [comment]
@ghilainm What versions are you using (e.g. Java, Gradle, Plugin)?

Incremental builds are supported in the plugin v2.5.0, but there is a bug (#36) that is causing an NPE for some users. The affected users have all backed out to plugin v2.4.1 until a PR to fix it is brought in.

**Comment by ghilainm** [comment]
Java 10
Plugin 2.5.2
Gradle 4.10.1 and gradle 5.0-20180925235833+0000

And does it support build caching? Because it seems it never uses it and it would be quite convenient as XSDs never change for me and the generation is slow :(.

**Comment by wdschei** [comment]
This plugin does not currently support [Gradle's build cache feature](https://docs.gradle.org/current/userguide/build_cache.html), but it does support [Gradle's up-to-date checks/incremental build feature](https://docs.gradle.org/current/userguide/more_about_tasks.html#sec:up_to_date_checks). So as long as your build is done locally, the XSD's don't change, and the _build_ directory is undisturbed, then a properly configured plugin should not re-run this task as it would be _up-to-date_.

I'm also a little confused on _"Plugin 2.5.2"_ since our latest release is **v2.5.0**.

**Comment by wdschei** [comment]
Issue closed due to lack of activity.
